name: update url_allowlist.csv

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        working-directory: ./test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run url_checker.py
        working-directory: ./test
        env:
          DC_API_KEY: ${{ secrets.DC_API_KEY }}
        run: python test/url_checker.py

      - name: create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update url_allowlist.csv
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-url
          delete-branch: true
          title: 'Update url_allowlist.csv'
          body: |
            Auto-update url_allowlist.csv with url_checker.yml
          labels: |
            report
            automated pr
