name: update url_allowlist.csv

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./test
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: execute py script # run url_checker.py
      #  env:
      #    DC_API_KEY: ${{ secrets.DC_API_KEY }}
      #  run: python url_checker.py --update_allowlist

      - name: test
        run: |
          printf ".env\n" > .gitignore

      - name: commit changes
        run: |
          git config --global user.name "datcom-bot"
          git config --global user.email "datcom-bot@users.noreply.github.com"
          git add --all
          git commit -am "Auto-update url_allowlist.csv: $(date)" 
          git push
