name: update url_allowlist.csv

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./test
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: execute py script # run url_checker.py
      #  env:
      #    DC_API_KEY: ${{ secrets.DC_API_KEY }}
      #  run: python url_checker.py --update_allowlist

      - name: test
        run: |
          printf ".env\n\n\n" > .gitignore

      #- name: create pull request
      #  uses: peter-evans/create-pull-request@v6
      #  with:
      #    commit-message: Update url_allowlist.csv
      #    committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
      #    author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
      #    signoff: false
      #    delete-branch: true
      #    title: 'Update url_allowlist.csv'
      #    body: |
      #      Auto-update url_allowlist.csv with url_checker.yml
      #    labels: |
      #      report
      #      automated pr

      - name: commit files
        run: |
          git config --local user.name "datcom-bot"
          git config --local user.email "datcom-bot@google.com"
          git add --all
          git commit -am "Update url_allowlist.csv: $(date)" 
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
